version: '3.7'
services:
    postgres:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - /var/lib/postgresql/data
